#!/bin/bash

if [ $(uname -s) = "Darwin" ]; then
  export GROOVY_HOME=$(brew --prefix groovy)/libexec
  export GRAILS_HOME=$(brew --prefix grails)/libexec
  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
  export PATH=${PATH}:${HOME}/.npm-packages/bin
  export PATH=${PATH}:${HOME}/Library/Python/2.7/bin
  export PATH=${PATH}:/usr/local/share/npm/bin
  export PATH=${PATH}:$HOME/.bin
  export PATH=${PATH}:${DEFAULT_PATH}
fi

if [ $(uname -s) = "Linux" ]; then
  export PATH=${PATH}:$(ruby -e "print Gem.user_dir")/bin
  export PATH=${PATH}:${HOME}/.local/bin
  export PATH=${PATH}:${HOME}/.npm-packages/bin
  export PATH=${PATH}:${HOME}/.bin
fi
